[INFO] [1740092466.880103763] [presence_Out_publisher]: Noeud PresenceOut Publisher : OK
[INFO] [1740092471.865911051] [presence_Out_publisher]: Exterieur : False
[INFO] [1740092476.865518439] [presence_Out_publisher]: Exterieur : False
[INFO] [1740092481.882547832] [presence_Out_publisher]: Exterieur : False
[INFO] [1740092486.870495729] [presence_Out_publisher]: Exterieur : True
[INFO] [1740092491.869465957] [presence_Out_publisher]: Exterieur : True
[INFO] [1740092496.879579082] [presence_Out_publisher]: Exterieur : True
Traceback (most recent call last):
  File "/home/thogms/ros2_ws/install/projet_pkg/lib/projet_pkg/publisher_presenceOut", line 33, in <module>
    sys.exit(load_entry_point('projet-pkg==0.0.0', 'console_scripts', 'publisher_presenceOut')())
  File "/home/thogms/ros2_ws/install/projet_pkg/lib/python3.10/site-packages/projet_pkg/publisher_presenceOut.py", line 34, in main
    rclpy.spin(presenceOut_publisher)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
    executor.spin_once()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 728, in _spin_once_impl
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 711, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 612, in _wait_for_ready_callbacks
    raise ExternalShutdownException()
rclpy.executors.ExternalShutdownException
[ros2run]: Process exited with failure 1
