[INFO] [1740092466.886329554] [time_publisher]: Noeud Time Publisher : OK
[INFO] [1740092471.878944861] [time_publisher]: Horaire : 13:34
[INFO] [1740092476.885337306] [time_publisher]: Horaire : 12:5
[INFO] [1740092481.901673869] [time_publisher]: Horaire : 6:28
[INFO] [1740092486.878839074] [time_publisher]: Horaire : 20:53
[INFO] [1740092491.878804088] [time_publisher]: Horaire : 9:8
[INFO] [1740092496.889925263] [time_publisher]: Horaire : 16:26
Traceback (most recent call last):
  File "/home/thogms/ros2_ws/install/projet_pkg/lib/projet_pkg/publisher_time", line 33, in <module>
    sys.exit(load_entry_point('projet-pkg==0.0.0', 'console_scripts', 'publisher_time')())
  File "/home/thogms/ros2_ws/install/projet_pkg/lib/python3.10/site-packages/projet_pkg/publisher_time.py", line 37, in main
    rclpy.spin(time_publisher)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
    executor.spin_once()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 728, in _spin_once_impl
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 711, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 612, in _wait_for_ready_callbacks
    raise ExternalShutdownException()
rclpy.executors.ExternalShutdownException
[ros2run]: Process exited with failure 1
